version: '3'
services:
  postgres: 
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=password
  redis:
    image: 'redis'
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /usr/server/node_modules
      - ./server:/usr/server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./fib-client
    volumes:
      - /usr/client/node_modules
      - ./fib-client:/usr/client
    ports:
      - "3000:3000"

  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /usr/worker/node_modules
      - ./worker:/usr/worker
